---
Author: Tímea Moder
Version: 1551-CNL 113 833, Rev. A
Date: 2016-04-05

---
= BSSGP v13.0.0 Protocol Modules for TTCN-3 Toolset with Titan, Description
:author: Tímea Moder
:revnumber: 1551-CNL 113 833, Rev. A
:revdate: 2016-04-05
:toc:

= Functionality

The BSSGP v13.0.0 protocol module implements the message structures of the related protocol <<_4, [4]>> in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

The BSSGP v13.0.0 protocol module uses Titan’s RAW encoding attributes <<_3, [3]>> and hence is usable with the Titan test toolset only.

== Implemented Protocols

This set of protocol modules implements protocol messages and constants of the BSSGP v13.0.0 protocol as described in <<_4, [4]>>.

=== Modified and Non-Implemented Protocol Elements

None.

== Backward Incompatibilities

None.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However, in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

Titan TTCN-3 Test Executor version CRL 113 200/5 R4A (5.4.pl0) or higher installed. For Installation Guide see <<_2, [2]>>.

NOTE: This version of the test port is not compatible with Titan releases earlier than CRL 113 200/5 R4A.

= Usage

== Installation

The set of protocol modules can be used in developing TTCN-3 test suites using any text editor; however, to make the work more efficient a TTCN3enabled text editor is recommended (for example `nedit`, `xemacs`). Since the BSSGP v13.0.0 protocol is used as a part of a TTCN-3 test suite, this requires TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<_2, [2]>>.

== Configuration

None.

== Examples

None.

= Interface Description

== Top Level PDU

The top level PDU is the TTCN-3 union `PDU_BSSGP`.

[[encoding-decoding-and-other-related-functions]]
== Encoding/Decoding and Other Related Functions

This product also contains encoding/decoding functions, which assure correct encoding of messages when sent from Titan and correct decoding of messages when received by Titan.

=== Implemented Encoding and Decoding Functions

[cols=3*,options=header]
|===

|Name |Type of formal parameters |Type of return value
|`enc_PDU_BSSGP` |in PDU_BSSGP |octetstring
|`dec_PDU_BSSGP` |in octetstring |PDU_BSSGP
|`dec_PDU_BSSGP_backtrack` |in octetstring, out PDU_BSSGP |integer
|`dec_PDU_BSSGP_fast` |in PDU_BSSGP, out octetstring |integer
|===

= Terminology

None.

== Abbreviations

PDU:: Protocol Data Unit

BSSGP:: BSS GPRS Protocol

BSS:: Base Station System

GPRS:: General Packet Radio Service

TTCN-3:: Testing and Test Control Notation version 3

= References

[[_1]]
[1] ETSI ES 201 873-1 v4.4.1 (2012-04) +
The Testing and Test Control Notation version 3. Part 1: Core Language

[[_2]]
[2] User Guide for TITAN TTCN-3 Test Executor

[[_3]]
[3] Programmer’s Technical Reference for Titan TTCN–3 Test Executor

[[_4]]
[4] 3GPP TS 48.018 v13.0.0 (2015-12) +
3rd Generation Partnership Project; Technical Specification GroupGSM/EDGE Radio Access Network; +
General Packet Radio Service (GPRS); +
Base Station System (BSS) - Serving GPRS Support Node (SGSN);BSS GPRS Protocol (BSSGP)(Release 13)
